# User Analytics in the Telecommunication Industry

## Import Libraries

In [1]:
## Import Libraries
import sys
import os
sys.path.append(os.path.abspath(os.path.join('..')))
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np 
from pandas.api.types import is_string_dtype, is_numeric_dtype

## Import Data

In [2]:
CSV_PATH = "../data/raw/rawData.csv"

In [3]:
# taking a csv file path and reading a dataframe

def read_proccessed_data(csv_path):
    try:    
        df = pd.read_csv(csv_path)
        print("file read as csv")
        return df
    except FileNotFoundError:
        print("file not found")

In [4]:
## getting number of columns, row and column information
def get_data_info(xDR_df: pd.DataFrame):
    
    row_count, col_count = xDR_df.shape
    
    print(f"Number of rows: {row_count}")
    print(f"Number of columns: {col_count}")

    return xDR_df.info()

In [5]:
## basic statistics of each column and see the data at glance
def get_statistics_info(xDR_df: pd.DataFrame):
    
    return xDR_df.describe(include='all')

In [6]:
# reading the extracted tweeter data and getting information

xDR_df = read_proccessed_data(CSV_PATH)
get_data_info(xDR_df)
get_statistics_info(xDR_df)

file read as csv
Number of rows: 150001
Number of columns: 55
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150001 entries, 0 to 150000
Data columns (total 55 columns):
 #   Column                                    Non-Null Count   Dtype
---  ------                                    --------------   -----
 0   Bearer Id                                 149010 non-null  float64
 1   Start                                     150000 non-null  object
 2   Start ms                                  150000 non-null  float64
 3   End                                       150000 non-null  object
 4   End ms                                    150000 non-null  float64
 5   Dur. (ms)                                 150000 non-null  float64
 6   IMSI                                      149431 non-null  float64
 7   MSISDN/Number                             148935 non-null  float64
 8   IMEI                                      149429 non-null  float64
 9   Last Location Name                        148848 non-null  object
 10  Avg RTT DL (ms)                           122172 non-null  float64
 11  Avg RTT UL (ms)                           122189 non-null  float64
 12  Avg Bearer TP DL (kbps)                   150000 non-null  float64
 13  Avg Bearer TP UL (kbps)                   150000 non-null  float64
 14  TCP DL Retrans. Vol (Bytes)               61855 non-null   float64
 15  TCP UL Retrans. Vol (Bytes)               53352 non-null   float64
 16  DL TP < 50 Kbps (%)                       149247 non-null  float64
 17  50 Kbps < DL TP < 250 Kbps (%)            149247 non-null  float64
 18  250 Kbps < DL TP < 1 Mbps (%)             149247 non-null  float64
 19  DL TP > 1 Mbps (%)                        149247 non-null  float64
 20  UL TP < 10 Kbps (%)                       149209 non-null  float64
 21  10 Kbps < UL TP < 50 Kbps (%)             149209 non-null  float64
 22  50 Kbps < UL TP < 300 Kbps (%)            149209 non-null  float64
 23  UL TP > 300 Kbps (%)                      149209 non-null  float64
 24  HTTP DL (Bytes)                           68527 non-null   float64
 25  HTTP UL (Bytes)                           68191 non-null   float64
 26  Activity Duration DL (ms)                 150000 non-null  float64
 27  Activity Duration UL (ms)                 150000 non-null  float64
 28  Dur. (ms).1                               150000 non-null  float64
 29  Handset Manufacturer                      149429 non-null  object
 30  Handset Type                              149429 non-null  object
 31  Nb of sec with 125000B < Vol DL           52463 non-null   float64
 32  Nb of sec with 1250B < Vol UL < 6250B     57107 non-null   float64
 33  Nb of sec with 31250B < Vol DL < 125000B  56415 non-null   float64
 34  Nb of sec with 37500B < Vol UL            19747 non-null   float64
 35  Nb of sec with 6250B < Vol DL < 31250B    61684 non-null   float64
 36  Nb of sec with 6250B < Vol UL < 37500B    38158 non-null   float64
 37  Nb of sec with Vol DL < 6250B             149246 non-null  float64
 38  Nb of sec with Vol UL < 1250B             149208 non-null  float64
 39  Social Media DL (Bytes)                   150001 non-null  float64
 40  Social Media UL (Bytes)                   150001 non-null  float64
 41  Google DL (Bytes)                         150001 non-null  float64
 42  Google UL (Bytes)                         150001 non-null  float64
 43  Email DL (Bytes)                          150001 non-null  float64
 44  Email UL (Bytes)                          150001 non-null  float64
 45  Youtube DL (Bytes)                        150001 non-null  float64
 46  Youtube UL (Bytes)                        150001 non-null  float64
 47  Netflix DL (Bytes)                        150001 non-null  float64
 48  Netflix UL (Bytes)                        150001 non-null  float64
 49  Gaming DL (Bytes)                         150001 non-null  float64
 50  Gaming UL (Bytes)                         150001 non-null  float64
 51  Other DL (Bytes)                          150001 non-null  float64
 52  Other UL (Bytes)                          150001 non-null  float64
 53  Total UL (Bytes)                          150000 non-null  float64
 54  Total DL (Bytes)                          150000 non-null  float64
dtypes: float64(50), object(5)
memory usage: 62.9+ MB

,Bearer Id,Start,Start ms,End,End ms,Dur. (ms),IMSI,MSISDN/Number,IMEI,Last Location Name,...,Youtube DL (Bytes),Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes),Total UL (Bytes),Total DL (Bytes)
count,1.490100e+05,150000,150000.000000,150000,150000.000000,1.500000e+05,1.494310e+05,1.489350e+05,1.494290e+05,148848,...,1.500010e+05,1.500010e+05,1.500010e+05,1.500010e+05,1.500010e+05,1.500010e+05,1.500010e+05,1.500010e+05,1.500000e+05,1.500000e+05
unique,NaN,9997,NaN,6403,NaN,NaN,NaN,NaN,NaN,45547,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,4/26/2019 7:25,NaN,4/25/2019 0:01,NaN,NaN,NaN,NaN,NaN,D41377B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,203,NaN,1150,NaN,NaN,NaN,NaN,NaN,80,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,1.013887e+19,NaN,499.188200,NaN,498.800880,1.046086e+05,2.082016e+14,4.188282e+10,4.847455e+13,NaN,...,1.163407e+07,1.100941e+07,1.162685e+07,1.100175e+07,4.220447e+08,8.288398e+06,4.211005e+08,8.264799e+06,4.112121e+07,4.546434e+08
std,2.893173e+18,NaN,288.611834,NaN,288.097653,8.103762e+04,2.148809e+10,2.447443e+12,2.241637e+13,NaN,...,6.710569e+06,6.345423e+06,6.725218e+06,6.359490e+06,2.439675e+08,4.782700e+06,2.432050e+08,4.769004e+06,1.127639e+07,2.441429e+08
min,6.917538e+18,NaN,0.000000,NaN,0.000000,7.142000e+03,2.040471e+14,3.360100e+10,4.400152e+11,NaN,...,5.300000e+01,1.050000e+02,4.200000e+01,3.500000e+01,2.516000e+03,5.900000e+01,3.290000e+03,1.480000e+02,2.866892e+06,7.114041e+06
25%,7.349883e+18,NaN,250.000000,NaN,251.000000,5.744050e+04,2.082014e+14,3.365130e+10,3.546071e+13,NaN,...,5.833501e+06,5.517965e+06,5.777156e+06,5.475981e+06,2.104733e+08,4.128476e+06,2.101869e+08,4.145943e+06,3.322201e+07,2.431068e+08
50%,7.349883e+18,NaN,499.000000,NaN,500.000000,8.639900e+04,2.082015e+14,3.366371e+10,3.572201e+13,NaN,...,1.161602e+07,1.101345e+07,1.164222e+07,1.099638e+07,4.234081e+08,8.291208e+06,4.218030e+08,8.267071e+06,4.114331e+07,4.558411e+08
75%,1.304243e+19,NaN,749.000000,NaN,750.000000,1.324302e+05,2.082018e+14,3.368349e+10,8.611970e+13,NaN,...,1.744852e+07,1.651556e+07,1.747048e+07,1.650727e+07,6.331742e+08,1.243162e+07,6.316918e+08,1.238415e+07,4.903424e+07,6.657055e+08
max,1.318654e+19,NaN,999.000000,NaN,999.000000,1.859336e+06,2.140743e+14,8.823971e+14,9.900120e+13,NaN,...,2.325910e+07,2.201196e+07,2.325919e+07,2.201196e+07,8.434419e+08,1.655879e+07,8.434425e+08,1.655882e+07,7.833131e+07,9.029696e+08

### Distinct value counts/frequencies of each column to determine if there are any columns with only a single value/all different values

In [7]:
pd.DataFrame(xDR_df.apply(lambda x: len(x.value_counts(dropna=False)), axis=0), 
columns=['Unique Value Count']).sort_values(by='Unique Value Count', ascending=True)

                                          Unique Value Count
UL TP > 300 Kbps (%)                                      64
50 Kbps < UL TP < 300 Kbps (%)                            69
250 Kbps < DL TP < 1 Mbps (%)                             74
50 Kbps < DL TP < 250 Kbps (%)                            85
10 Kbps < UL TP < 50 Kbps (%)                             86
DL TP > 1 Mbps (%)                                        86
UL TP < 10 Kbps (%)                                       99
DL TP < 50 Kbps (%)                                      101
Handset Manufacturer                                     171
Avg RTT UL (ms)                                          723
Start ms                                                1001
End ms                                                  1001
Nb of sec with 37500B < Vol UL                          1105
Handset Type                                            1397
Nb of sec with 6250B < Vol UL < 37500B                  1711
Avg RTT DL (ms)                                         2131
Nb of sec with 1250B < Vol UL < 6250B                   3399
Nb of sec with 31250B < Vol DL < 125000B                5756
Nb of sec with 6250B < Vol DL < 31250B                  6173
End                                                     6404
Nb of sec with 125000B < Vol DL                         6459
Start                                                   9998
Avg Bearer TP UL (kbps)                                14529
Nb of sec with Vol DL < 6250B                          22271
Nb of sec with Vol UL < 1250B                          22977
TCP UL Retrans. Vol (Bytes)                            35121
Avg Bearer TP DL (kbps)                                41754
Last Location Name                                     45548
TCP DL Retrans. Vol (Bytes)                            54400
Social Media UL (Bytes)                                59078
HTTP UL (Bytes)                                        59943
HTTP DL (Bytes)                                        63528
Dur. (ms)                                              89526
Activity Duration DL (ms)                             102561
Activity Duration UL (ms)                             106293
MSISDN/Number                                         106857
IMSI                                                  107266
IMEI                                                  107271
Dur. (ms).1                                           122872
Bearer Id                                             134709
Email UL (Bytes)                                      138699
Social Media DL (Bytes)                               146856
Email DL (Bytes)                                      146916
Google UL (Bytes)                                     147267
Google DL (Bytes)                                     149024
Other UL (Bytes)                                      149284
Gaming UL (Bytes)                                     149316
Youtube UL (Bytes)                                    149477
Netflix UL (Bytes)                                    149490
Netflix DL (Bytes)                                    149518
Youtube DL (Bytes)                                    149547
Total UL (Bytes)                                      149729
Gaming DL (Bytes)                                     149983
Other DL (Bytes)                                      149986
Total DL (Bytes)                                      149988

In [8]:
xDR_df.isnull().sum()

Bearer Id                                      991
Start                                            1
Start ms                                         1
End                                              1
End ms                                           1
Dur. (ms)                                        1
IMSI                                           570
MSISDN/Number                                 1066
IMEI                                           572
Last Location Name                            1153
Avg RTT DL (ms)                              27829
Avg RTT UL (ms)                              27812
Avg Bearer TP DL (kbps)                          1
Avg Bearer TP UL (kbps)                          1
TCP DL Retrans. Vol (Bytes)                  88146
TCP UL Retrans. Vol (Bytes)                  96649
DL TP < 50 Kbps (%)                            754
50 Kbps < DL TP < 250 Kbps (%)                 754
250 Kbps < DL TP < 1 Mbps (%)                  754
DL TP > 1 Mbps (%)                             754
UL TP < 10 Kbps (%)                            792
10 Kbps < UL TP < 50 Kbps (%)                  792
50 Kbps < UL TP < 300 Kbps (%)                 792
UL TP > 300 Kbps (%)                           792
HTTP DL (Bytes)                              81474
HTTP UL (Bytes)                              81810
Activity Duration DL (ms)                        1
Activity Duration UL (ms)                        1
Dur. (ms).1                                      1
Handset Manufacturer                           572
Handset Type                                   572
Nb of sec with 125000B < Vol DL              97538
Nb of sec with 1250B < Vol UL < 6250B        92894
Nb of sec with 31250B < Vol DL < 125000B     93586
Nb of sec with 37500B < Vol UL              130254
Nb of sec with 6250B < Vol DL < 31250B       88317
Nb of sec with 6250B < Vol UL < 37500B      111843
Nb of sec with Vol DL < 6250B                  755
Nb of sec with Vol UL < 1250B                  793
Social Media DL (Bytes)                          0
Social Media UL (Bytes)                          0
Google DL (Bytes)                                0
Google UL (Bytes)                                0
Email DL (Bytes)                                 0
Email UL (Bytes)                                 0
Youtube DL (Bytes)                               0
Youtube UL (Bytes)                               0
Netflix DL (Bytes)                               0
Netflix UL (Bytes)                               0
Gaming DL (Bytes)                                0
Gaming UL (Bytes)                                0
Other DL (Bytes)                                 0
Other UL (Bytes)                                 0
Total UL (Bytes)                                 1
Total DL (Bytes)                                 1
dtype: int64

In [9]:
def percent_missing(df):

    totalCells = np.product(df.shape)
    missingCount = df.isnull().sum()
    totalMissing = missingCount.sum()
    return round((totalMissing / totalCells) * 100, 2)

In [10]:

print("The Telco Telecom dataset contains", percent_missing(xDR_df), "%", "missing values.")

The Telco Telecom dataset contains 12.5 % missing values.

In [11]:
def percent_missing_for_col(df, col_name: str):
    total_count = len(df[col_name])
    if total_count <= 0:
        return 0.0
    missing_count = df[col_name].isnull().sum()
    
    return round((missing_count / total_count) * 100, 2)

In [12]:
null_percent_df = pd.DataFrame(columns = ['column', 'null_percent'])
columns = xDR_df.columns.values.tolist()
null_percent_df['column'] = columns
null_percent_df['null_percent'] = null_percent_df['column'].map(lambda x: percent_missing_for_col(xDR_df, x))

In [13]:
null_percent_df.sort_values(by=['null_percent'], ascending = False)

                                      column  null_percent
34            Nb of sec with 37500B < Vol UL         86.84
36    Nb of sec with 6250B < Vol UL < 37500B         74.56
31           Nb of sec with 125000B < Vol DL         65.02
15               TCP UL Retrans. Vol (Bytes)         64.43
33  Nb of sec with 31250B < Vol DL < 125000B         62.39
32     Nb of sec with 1250B < Vol UL < 6250B         61.93
35    Nb of sec with 6250B < Vol DL < 31250B         58.88
14               TCP DL Retrans. Vol (Bytes)         58.76
25                           HTTP UL (Bytes)         54.54
24                           HTTP DL (Bytes)         54.32
10                           Avg RTT DL (ms)         18.55
11                           Avg RTT UL (ms)         18.54
9                         Last Location Name          0.77
7                              MSISDN/Number          0.71
0                                  Bearer Id          0.66
21             10 Kbps < UL TP < 50 Kbps (%)          0.53
38             Nb of sec with Vol UL < 1250B          0.53
23                      UL TP > 300 Kbps (%)          0.53
22            50 Kbps < UL TP < 300 Kbps (%)          0.53
20                       UL TP < 10 Kbps (%)          0.53
18             250 Kbps < DL TP < 1 Mbps (%)          0.50
17            50 Kbps < DL TP < 250 Kbps (%)          0.50
16                       DL TP < 50 Kbps (%)          0.50
37             Nb of sec with Vol DL < 6250B          0.50
19                        DL TP > 1 Mbps (%)          0.50
30                              Handset Type          0.38
29                      Handset Manufacturer          0.38
8                                       IMEI          0.38
6                                       IMSI          0.38
50                         Gaming UL (Bytes)          0.00
44                          Email UL (Bytes)          0.00
53                          Total UL (Bytes)          0.00
52                          Other UL (Bytes)          0.00
51                          Other DL (Bytes)          0.00
42                         Google UL (Bytes)          0.00
49                         Gaming DL (Bytes)          0.00
45                        Youtube DL (Bytes)          0.00
46                        Youtube UL (Bytes)          0.00
47                        Netflix DL (Bytes)          0.00
48                        Netflix UL (Bytes)          0.00
43                          Email DL (Bytes)          0.00
27                 Activity Duration UL (ms)          0.00
41                         Google DL (Bytes)          0.00
40                   Social Media UL (Bytes)          0.00
39                   Social Media DL (Bytes)          0.00
28                               Dur. (ms).1          0.00
1                                      Start          0.00
26                 Activity Duration DL (ms)          0.00
13                   Avg Bearer TP UL (kbps)          0.00
12                   Avg Bearer TP DL (kbps)          0.00
5                                  Dur. (ms)          0.00
4                                     End ms          0.00
3                                        End          0.00
2                                   Start ms          0.00
54                          Total DL (Bytes)          0.00

In [14]:
#Drop columns with morethan 30% missing values
def drop_columns(xDR_df, columns=[]):
    return xDR_df.drop(columns, axis=1)

In [15]:
columns_to_be_dropped = null_percent_df[null_percent_df['null_percent'] > 30]['column'].to_list()
xDR_df = drop_columns(xDR_df, columns_to_be_dropped)

In [16]:
def percent_missing(df):

    totalCells = np.product(df.shape)
    missingCount = df.isnull().sum()
    totalMissing = missingCount.sum()
    return round((totalMissing / totalCells) * 100, 2)

In [18]:
print("The Telco Telecom dataset contains", percent_missing(xDR_df), "%", "missing values.")

The Telco Telecom dataset contains 1.02 % missing values.

In [21]:
xDR_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150001 entries, 0 to 150000
Data columns (total 45 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   Bearer Id                       149010 non-null  float64
 1   Start                           150000 non-null  object
 2   Start ms                        150000 non-null  float64
 3   End                             150000 non-null  object
 4   End ms                          150000 non-null  float64
 5   Dur. (ms)                       150000 non-null  float64
 6   IMSI                            149431 non-null  float64
 7   MSISDN/Number                   148935 non-null  float64
 8   IMEI                            149429 non-null  float64
 9   Last Location Name              148848 non-null  object
 10  Avg RTT DL (ms)                 122172 non-null  float64
 11  Avg RTT UL (ms)                 122189 non-null  float64
 12  Avg Bearer TP DL (kbps)         150000 non-null  float64
 13  Avg Bearer TP UL (kbps)         150000 non-null  float64
 14  DL TP < 50 Kbps (%)             149247 non-null  float64
 15  50 Kbps < DL TP < 250 Kbps (%)  149247 non-null  float64
 16  250 Kbps < DL TP < 1 Mbps (%)   149247 non-null  float64
 17  DL TP > 1 Mbps (%)              149247 non-null  float64
 18  UL TP < 10 Kbps (%)             149209 non-null  float64
 19  10 Kbps < UL TP < 50 Kbps (%)   149209 non-null  float64
 20  50 Kbps < UL TP < 300 Kbps (%)  149209 non-null  float64
 21  UL TP > 300 Kbps (%)            149209 non-null  float64
 22  Activity Duration DL (ms)       150000 non-null  float64
 23  Activity Duration UL (ms)       150000 non-null  float64
 24  Dur. (ms).1                     150000 non-null  float64
 25  Handset Manufacturer            149429 non-null  object
 26  Handset Type                    149429 non-null  object
 27  Nb of sec with Vol DL < 6250B   149246 non-null  float64
 28  Nb of sec with Vol UL < 1250B   149208 non-null  float64
 29  Social Media DL (Bytes)         150001 non-null  float64
 30  Social Media UL (Bytes)         150001 non-null  float64
 31  Google DL (Bytes)               150001 non-null  float64
 32  Google UL (Bytes)               150001 non-null  float64
 33  Email DL (Bytes)                150001 non-null  float64
 34  Email UL (Bytes)                150001 non-null  float64
 35  Youtube DL (Bytes)              150001 non-null  float64
 36  Youtube UL (Bytes)              150001 non-null  float64
 37  Netflix DL (Bytes)              150001 non-null  float64
 38  Netflix UL (Bytes)              150001 non-null  float64
 39  Gaming DL (Bytes)               150001 non-null  float64
 40  Gaming UL (Bytes)               150001 non-null  float64
 41  Other DL (Bytes)                150001 non-null  float64
 42  Other UL (Bytes)                150001 non-null  float64
 43  Total UL (Bytes)                150000 non-null  float64
 44  Total DL (Bytes)                150000 non-null  float64
dtypes: float64(40), object(5)
memory usage: 51.5+ MB

# # Task 1.1 - Your employer wants to have an overview of the users’ behavior on those applications.   
### Aggregate per user the following information in the column  
    number of xDR sessions
    Session duration
    the total download (DL) and upload (UL) data
    the total data volume (in Bytes) during this session for each application

In [24]:
xDR_df.sample(5)

,Bearer Id,Start,Start ms,End,End ms,Dur. (ms),IMSI,MSISDN/Number,IMEI,Last Location Name,...,Youtube DL (Bytes),Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes),Total UL (Bytes),Total DL (Bytes)
58865,7.349883e+18,4/26/2019 1:12,110.0,4/27/2019 15:55,887.0,139407.0,2.082014e+14,3.363282e+10,3.596031e+13,T73288B,...,5112902.0,14273544.0,22292532.0,21848203.0,779674971.0,4757943.0,188559043.0,2473097.0,46307345.0,811267789.0
130775,7.349883e+18,4/28/2019 12:08,837.0,4/30/2019 15:16,560.0,184064.0,2.082022e+14,3.363252e+10,3.574631e+13,T88792B,...,5517776.0,8128842.0,20665597.0,5464329.0,827526994.0,13840042.0,593497256.0,1700895.0,32250861.0,862499488.0
50121,7.349883e+18,4/21/2019 9:42,733.0,4/27/2019 7:34,670.0,510712.0,2.082010e+14,3.365852e+10,3.591441e+13,D10111A,...,4404426.0,2239753.0,22800286.0,1794950.0,663336864.0,13773807.0,20723359.0,151583.0,18128029.0,695618252.0
59216,1.304243e+19,4/26/2019 1:46,10.0,4/27/2019 1:46,927.0,86399.0,2.082018e+14,3.366415e+10,8.637690e+13,D92963B,...,8478416.0,20199907.0,10036289.0,19170495.0,379286351.0,14732371.0,166718650.0,14466740.0,70725378.0,412749534.0
64669,1.311448e+19,4/26/2019 7:20,419.0,4/27/2019 10:52,673.0,99102.0,2.082014e+14,3.366053e+10,3.553961e+13,D53406A,...,22709435.0,12396705.0,9943887.0,17147045.0,271403328.0,5168562.0,147187214.0,1266260.0,37721099.0,313341253.0

### Number of xDR sessions

In [23]:
xDR_df.groupby('MSISDN/Number')['Bearer Id'].count().nlargest(10)

MSISDN/Number
3.362632e+10    18
3.361489e+10    17
3.362578e+10    17
3.365973e+10    16
3.367588e+10    15
3.376054e+10    15
3.366716e+10    13
3.360313e+10    12
3.360452e+10    12
3.362708e+10    12
Name: Bearer Id, dtype: int64

## Session duration

In [27]:
xDR_df.groupby('MSISDN/Number')['Dur. (ms)'].sum().nlargest(10)

MSISDN/Number
3.362578e+10    18553754.0
3.361489e+10     9966898.0
3.376054e+10     9279434.0
3.362632e+10     8791927.0
3.366716e+10     8744914.0
3.366284e+10     6614270.0
3.366469e+10     6288730.0
3.360313e+10     6287761.0
3.366746e+10     5649882.0
3.376041e+10     5321667.0
Name: Dur. (ms), dtype: float64

## the total download (DL) and upload (UL) data

In [29]:
xDR_df.groupby('MSISDN/Number')[['Total DL (Bytes)',
                             'Total UL (Bytes)']].sum().nlargest(10, ['Total DL (Bytes)',
                                                                      'Total UL (Bytes)'])

               Total DL (Bytes)  Total UL (Bytes)
MSISDN/Number
3.361489e+10       8.156743e+09       689483001.0
3.376054e+10       7.811295e+09       703478581.0
3.362578e+10       7.770043e+09       729577380.0
3.367588e+10       7.309542e+09       581568792.0
3.362632e+10       7.301517e+09       669650721.0
3.365973e+10       7.081602e+09       624260321.0
3.366646e+10       6.903440e+09       405060976.0
3.376041e+10       6.610852e+09       521518890.0
3.366471e+10       6.400774e+09       471244453.0
3.369879e+10       6.010556e+09       530343105.0

## the total data volume (in Bytes) during this session

In [32]:
xDR_df["total_data_usage"] = xDR_df["Total DL (Bytes)"] + xDR_df["Total UL (Bytes)"]
xDR_df.groupby('MSISDN/Number')['total_data_usage'].sum().nlargest(10)

MSISDN/Number
3.361489e+10    8.846226e+09
3.376054e+10    8.514774e+09
3.362578e+10    8.499621e+09
3.362632e+10    7.971167e+09
3.367588e+10    7.891111e+09
3.365973e+10    7.705863e+09
3.366646e+10    7.308501e+09
3.376041e+10    7.132371e+09
3.366471e+10    6.872018e+09
3.369879e+10    6.540899e+09
Name: total_data_usage, dtype: float64

### the total data volume (in Bytes) during this session Social Media apps

In [33]:
xDR_df["total_data_usage"] = xDR_df["Social Media DL (Bytes)"] + xDR_df["Social Media UL (Bytes)"]
xDR_df.groupby('MSISDN/Number')['total_data_usage'].sum().nlargest(10)

MSISDN/Number
3.362632e+10    43374779.0
3.376054e+10    39783189.0
3.365973e+10    35412358.0
3.361489e+10    28294544.0
3.362578e+10    27135500.0
3.366716e+10    24247850.0
3.378632e+10    23974919.0
3.366907e+10    23800834.0
3.360313e+10    23077825.0
3.365849e+10    23000066.0
Name: total_data_usage, dtype: float64

### the total data volume (in Bytes) during this session YouTube

In [36]:
xDR_df["total_data_usage"] = xDR_df["Youtube DL (Bytes)"] + xDR_df["Youtube UL (Bytes)"]
xDR_df.groupby('MSISDN/Number')['total_data_usage'].sum().nlargest(10)

MSISDN/Number
3.362578e+10    452958769.0
3.376054e+10    396289198.0
3.361489e+10    394370218.0
3.362632e+10    374483047.0
3.367588e+10    317410572.0
3.366716e+10    315231310.0
3.362708e+10    308790774.0
3.376041e+10    303169107.0
3.369879e+10    302661958.0
3.360313e+10    284090139.0
Name: total_data_usage, dtype: float64

### the total data volume (in Bytes) during this session Netflix

In [37]:
xDR_df["total_data_usage"] = xDR_df["Netflix DL (Bytes)"] + xDR_df["Netflix UL (Bytes)"]
xDR_df.groupby('MSISDN/Number')['total_data_usage'].sum().nlargest(10)

MSISDN/Number
3.365973e+10    399519079.0
3.361489e+10    361401046.0
3.362578e+10    356980607.0
3.376054e+10    334643269.0
3.362632e+10    328725740.0
3.376041e+10    318347546.0
3.366716e+10    313939488.0
3.367588e+10    309093159.0
3.378632e+10    305939790.0
3.376127e+10    292091341.0
Name: total_data_usage, dtype: float64

### the total data volume (in Bytes) during this session Google

In [38]:
xDR_df["total_data_usage"] = xDR_df["Google DL (Bytes)"] + xDR_df["Google UL (Bytes)"]
xDR_df.groupby('MSISDN/Number')['total_data_usage'].sum().nlargest(10)

MSISDN/Number
3.362632e+10    152191852.0
3.362578e+10    142307915.0
3.361489e+10    127973787.0
3.376054e+10    123223099.0
3.365973e+10    116516345.0
3.378632e+10    110254484.0
3.367588e+10    109860502.0
3.366716e+10    105032696.0
3.376127e+10     97089988.0
3.369876e+10     91935151.0
Name: total_data_usage, dtype: float64

### the total data volume (in Bytes) during this session Email

In [39]:
xDR_df["total_data_usage"] = xDR_df["Email DL (Bytes)"] + xDR_df["Email UL (Bytes)"]
xDR_df.groupby('MSISDN/Number')['total_data_usage'].sum().nlargest(10)

MSISDN/Number
3.362632e+10    42418782.0
3.361489e+10    40788634.0
3.362578e+10    40633966.0
3.378632e+10    36310123.0
3.365973e+10    35999792.0
3.376054e+10    33693767.0
3.367588e+10    31514421.0
3.366546e+10    30417885.0
3.366716e+10    30335796.0
3.369879e+10    29059042.0
Name: total_data_usage, dtype: float64

### the total data volume (in Bytes) during this session Gaming

In [40]:
xDR_df["total_data_usage"] = xDR_df["Gaming DL (Bytes)"] + xDR_df["Gaming DL (Bytes)"]
xDR_df.groupby('MSISDN/Number')['total_data_usage'].sum().nlargest(10)

MSISDN/Number
3.361489e+10    1.524407e+10
3.376054e+10    1.463273e+10
3.362578e+10    1.434377e+10
3.367588e+10    1.372661e+10
3.362632e+10    1.349147e+10
3.365973e+10    1.321980e+10
3.366646e+10    1.309266e+10
3.376041e+10    1.234189e+10
3.366471e+10    1.202712e+10
3.369879e+10    1.128226e+10
Name: total_data_usage, dtype: float64